<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDZ3tGor\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDZ3tGor/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDZ3tGor.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDZ3tGor\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDZ3tGor\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DZ3tGor',
    'container.build_id' => '08acf47f',
    'container.build_time' => 1658223763,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDZ3tGor');
